### ISSUE TITLE
Rewrite all of the code so i dont have to use k8s

### ISSUE THREAD

**Issue by Releasement** [minilauta/miniboard#90]
It's gay and I don't understand how to use it therefore no one should use it.

**Comment by Anonyymi** [comment]
It should work fine without kubernetes, but if you want an easy to use imageboard script then you should probably use something like the original Futaba script, some modern derivative of it.

But if you want to work on it to make it easily installable directly on a linux server without any container stuff, you are free to submit changes. :-)
